import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';
import { PlausibleAnalytics } from '@/components/analytics/PlausibleAnalytics';
import { OrganizationJsonLd, WebSiteJsonLd } from '@/components/seo/JsonLd';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    default: 'CLAIR.vote - Transparence Politique en France',
    template: '%s | CLAIR.vote',
  },
  description: 'CLAIR.vote : analysez les votes des députés et sénateurs, suivez le lobbying et la transparence politique en France. Plateforme citoyenne gratuite.',
  keywords: ['politique', 'france', 'parlementaires', 'députés', 'sénateurs', 'votes', 'assemblée nationale', 'sénat', 'lobbying', 'transparence'],
  authors: [{ name: 'CLAIR' }],
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'https://clair.vote'),
  icons: {
    icon: [
      { url: '/favicon.ico', sizes: '48x48' },
      { url: '/icon.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/apple-icon.png',
  },
  openGraph: {
    title: 'CLAIR.vote - Transparence Politique en France',
    description: 'CLAIR.vote : analysez les votes des députés et sénateurs, suivez le lobbying et la transparence politique en France.',
    type: 'website',
    locale: 'fr_FR',
    siteName: 'CLAIR.vote',
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CLAIR.vote - Transparence Politique en France',
    description: 'CLAIR.vote : analysez les votes des députés et sénateurs, suivez le lobbying et la transparence politique en France.',
    // Image auto-generated by app/opengraph-image.tsx
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <head>
        <OrganizationJsonLd />
        <WebSiteJsonLd />
      </head>
      <body className={`${inter.className} min-h-screen bg-background antialiased`}>
        <PlausibleAnalytics />
        <Providers>
          <div className="relative flex min-h-screen flex-col">
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
